### ISSUE TITLE
ID review feedback

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/guide-reactive-service-testing#42]
My feedback is included in the attached Word document. As always, read through my suggestions and make sure they make sense to you. Feel free to reach out to me with any questions. Thanks!

[Testing reactive Java microservices-ID-feedback.docx](https://github.com/OpenLiberty/draft-guide-reactive-service-testing/files/4558239/Testing.reactive.Java.microservices-ID-feedback.docx)

**Comment by MaiHameed** [comment]
> In “MicroShed Testing and Kafka test containers have already been included as required test dependencies in your Maven pom.xml files for the system and inventory services.”, should “test containers” be “Testcontainers”. I found this documentation, but I’m not sure if it applies to this scenario.

> Question
Same question as my previous one about the use of “test container” in “Later in the guide, you will write and run tests that start a Kafka test container for the system service to communicate.”

You're right, it can apply here, I updated the sections.

> Change
Start Open Liberty in development mode, which starts the Open Liberty server and listens for file changes:
To
Starting Open Liberty in dev mode starts the Open Liberty server and listens for file changes. Run the following command to start in dev mode:

> Change
After you see the following message, your application server in development mode is ready.
To
After you see the following message, your application server in dev mode is ready:

> Change
The development mode holds your command prompt to listen for file changes. You need to open another command prompt to continue, or simply open the project in your editor.
To
Dev mode holds your command line to listen for file changes. Open another command line to continue, or open the project in your editor.

This changes the default included file on dev mode, found here: https://github.com/OpenLiberty/guides-common/blob/master/devmode-start.adoc that has been reviewed already. This paragraph block is used across multiple guides. If you still think that it's a valuable change let me know and I can update it.

> Question
Is dependsOn() really an annotation here? It seems like annotations begin with @. Maybe this is a property (or something) of the annotation?

You're right, it is not an annotation, I replaced `annotation` with `method`.

> Question
Are you referring to the the valueDeserializer of multiple consumers in “The deserializer is configured to the consumers’ valueDeserializer and is implemented in the SystemLoad class.”? If so, then this is good how it is. If not, it should be, “The deserializer is configured to the consumer’s valueDeserializer and is implemented in the SystemLoad class.”

Just the one consumer. Changed `consumers' to consumer's`.

> Change
The testCpuStatus() test method polls records from Kafka every three seconds until the timeout limit. It then verifies that the record polled matches the expected record.
To
The testCpuStatus() test method polls records from Kafka every 3 seconds until the timeout limit. It then verifies that each record that was polled matches the expected record.

I made a mistake, the method will only poll a single record, not multiple. I rewrote the sentence to:

> The testCpuStatus() test method polls a record from Kafka every three seconds until the timeout limit. It then verifies that the record polled matches the expected record.

Let me know if this works.

> Change
Since you started Open Liberty in development mode at the start of the guide, press the enter/return key to run the tests.
To
Since you started Open Liberty in dev mode, press the enter/return key to run the tests.

This is also taken from the common included paragraph here: https://github.com/OpenLiberty/guides-common/blob/master/devmode-test.adoc

> Question
Should “Kafka” be capitalized as the container name in the previous sentence? I believe the container for the system service called “kafka” wasn’t capitalized. (This capitalization could be to differentiate them, but I just wanted to check.)

I didn't capitalize it to differentiate the Kafka container `kafka` which is configured and named in the `AppContainerConfig` class from the actual application Kafka. Hopefully this makes sense? I kept it lowercased.

**Comment by Charlotte-Holt** [comment]
@MaiHameed Changes look good. Thanks! I added just three quick things inline in the PR. I do think we should update the development mode docs that are included here to mention 'dev' mode, rather than 'development' mode. These are the updates I'd suggest for those: 

Change
Start Open Liberty in development mode, which starts the Open Liberty server and listens for file changes:
To
When you run Open Liberty in dev mode, the server listens for file changes and automatically recompiles and deploys your updates whenever you save a new change. Run the following goal to start in dev mode:

Change
After you see the following message, your application server in development mode is ready.
To
After you see the following message, your application server in dev mode is ready:

Change
The development mode holds your command prompt to listen for file changes. You need to open another command prompt to continue, or simply open the project in your editor.
To
Dev mode holds your command line to listen for file changes. Open another command line to continue, or open the project in your editor.

Change
Since you started Open Liberty in development mode at the start of the guide, press the enter/return key to run the tests.
To
Since you started Open Liberty in dev mode, press the enter/return key to run the tests.

**Comment by MaiHameed** [comment]
Addressed and resolved.
